### ISSUE TITLE
(ERROR) Task never defined: Default

### ISSUE THREAD

**Issue by e-g-b** [thecodercoder/frontend-boilerplate#1]
I tried going through your frontend-boilerplate demo and get an error when trying to run the "gulp" command. I'm unable to run the project beyond this task, which says it's not defined.

![Screen Shot 2019-05-14 at 1 46 46 PM](https://user-images.githubusercontent.com/3340761/57720040-1054d600-764f-11e9-98c8-0c01bcb382f1.png)

**Comment by ghost** [comment]
it's because of "gulp": "4.0.0", update to latest version "gulp": "^4.0.2"

**Comment by thecodercoder** [comment]
@e-g-b Were you able to get this resolved? If not, let me know if you ran `npm install` and what versions of Gulp and Node you have installed.

**Comment by LiubovBahatchenko** [comment]
I`ve had the same problem when i tried to run default task.

**Comment by mbalazy** [comment]
I had the same problem. Like @Im-Prashant said: open package.json before npm install and change gulp version to 4.0.2.

**Comment by thecodercoder** [comment]
I updated the package.json file to allow for minor updates to the gulp npm package, so it won't be stuck on v4.0.0. This should fix this issue. Thanks @Im-Prashant!

**Comment by e-g-b** [comment]
@thecodercoder Ran your update and can confirm it works for me now. Thanks!
