### ISSUE TITLE
Recommend switching from gulp-uglify to gulp-terser-js

### ISSUE THREAD

**Issue by janusoo** [thecodercoder/frontend-boilerplate#5]
First, I love your boilerplate! It's simple and easy to understand. And your Youtube tutorial highlighting this was equally so.

I'm using it now with some slight modifications and it works great!

The issue: I encountered a JavaScript minification error which revealed that gulp-uglify could not handle ES6 syntax:
![image](https://user-images.githubusercontent.com/12981937/81510350-00fa7e00-92df-11ea-8bec-44b4eb90b41e.png)
 This led me on a little journey with stops at gulp-uglify-es, terser (recommended as the gulp-uglify-es successor by the folks who made it)...
![image](https://user-images.githubusercontent.com/12981937/81510750-18873600-92e2-11ea-9de4-de305652ca7a.png)

![image](https://user-images.githubusercontent.com/12981937/81510769-56845a00-92e2-11ea-9351-a65f7dc38303.png)

Eventually, I found my way to gulp-terser, which seems to be the gulp optimized version of terser. This finally allowed the gulp task to complete. But it looks like the last update was over a year ago.

So finally I found gulp-terser-js, which handles ES6 syntax well and is actively being maintained at present:
![image](https://user-images.githubusercontent.com/12981937/81511282-39ea2100-92e6-11ea-85cc-5fe41a246a97.png)

**Comment by thecodercoder** [comment]
We are now using gulp-terser to minify JS! 🎉
